### ISSUE TITLE
Upload from JSONL does not work

### ISSUE THREAD

**Issue by mojito317** [chakki-works/doccano#166]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Win10
- **Python version**:  Python 3.6.6

### Describe the problem
I have a syntactically correct file for uploading as JSONL, but I cannot upload it. The data does not appear in my annotations.
### Source code / logs

- example  of the file:
```
{"text": "!.It's just a very poor show that may have seemed like an ambitious turn of events back in the mid 1980s; but when viewing the three films together now, Thunderdome just comes across as a director losing his edgy approach whilst sadly getting caught between the mix of comedy and fantasy action.", "labels": [ [127, 132, "CARDINAL"] ]}
{"text": "!First of all I watch a lot Lifetime movies and realize they are just that....Lifetime movies.", "labels": [ [28, 36, "ORG"], [78, 86, "ORG"] ]}
{"text": "1 out of 10.", "labels": [ [9, 11, "CARDINAL"], [9, 11, "CARDINAL"], [9, 11, "CARDINAL"] ]}
```

- logs from server:

```
Internal Server Error: /v1/projects/4/docs/upload
Traceback (most recent call last):
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\backends\sqlite3\base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: server_sequenceannotation.document_id, server_sequenceannotation.user_id, server_sequenceannotation.label_id, server_sequenceannotation.start_offset, server_sequenceannotation.end_offset

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "...\Dev\doccano\app\server\api.py", line 187, in post
    storage.save(self.request.user)
  File "...\AppData\Local\Programs\Python\Python36\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "...\Dev\doccano\app\server\utils.py", line 177, in save
    self.save_annotation(annotations, user)
  File "...\Dev\doccano\app\server\utils.py", line 53, in save_annotation
    annotation = serializer.save(user=user)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\rest_framework\serializers.py", line 728, in save
    self.instance = self.create(validated_data)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\rest_framework\serializers.py", line 700, in create
    self.child.create(attrs) for attrs in validated_data
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\rest_framework\serializers.py", line 700, in <listcomp>
    self.child.create(attrs) for attrs in validated_data
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\rest_framework\serializers.py", line 940, in create
    instance = ModelClass.objects.create(**validated_data)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\sql\compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\backends\sqlite3\base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: server_sequenceannotation.document_id, server_sequenceannotation.user_id, server_sequenceannotation.label_id, server_sequenceannotation.start_offset, server_sequenceannotation.end_offset
[18/Apr/2019 10:11:33] "POST /v1/projects/4/docs/upload HTTP/1.1" 500 25551
```

**Comment by Hironsan** [comment]
doccano does not allow overlapping label. So you cannot upload the following format:

```
{"text": "1 out of 10.", "labels": [ [9, 11, "CARDINAL"], [9, 11, "CARDINAL"], [9, 11, "CARDINAL"] ]}
```

**Comment by mojito317** [comment]
@Hironsan Thanks for the quick reply. I removed the duplications, it was the problem.

**Comment by swicaksono** [comment]
@Hironsan Thanks for this response. But if I want to customize, so doccano can do the annotation task that consist of overlapping labels, is it possible?
