### ISSUE TITLE
WSGI Module not working

### ISSUE THREAD

**Issue by NatashaSvic** [chakki-works/doccano#188]
### System information
- **MacOS  Mojave 10.14**:
- **Python Version 3.6**: 

### Problem
When I execute the manage.py I get the following error related to the WSGI app. I checked the app/settings.py & wsgi.py file and they seem fine. 

### Source code / logs
natashas-mbp:app user$ python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
May 06, 2019 - 14:18:41
Django version 2.0, using settings 'app.settings'
Starting development server at <LOCALHOST>
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x111182f28>
Traceback (most recent call last):
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 44, in get_internal_wsgi_application
    return import_string(app_path)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/Users/user/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/user/doccano/app/app/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 140, in __init__
    self.load_middleware()
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 37, in load_middleware
    middleware = import_string(middleware_path)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/Users/user/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'applicationinsights'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 140, in inner_run
    handler = self.get_handler(*args, **options)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 65, in get_handler
    return get_internal_wsgi_application()
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 49, in get_internal_wsgi_application
    ) from err
django.core.exceptions.ImproperlyConfigured: WSGI application 'app.wsgi.application' could not be loaded; Error importing module.

**Comment by Hironsan** [comment]
It seems to me that `applicationinsights` package is not installed.

Please run:

```bash
pip install -r requirements.txt
```

**Comment by NatashaSvic** [comment]
Thanks for your response!

I executed the requirements.txt including all the Django dependencies that were not included in the txt and was able to start the server now. Yet, there's still this error after `python manage.py runserver` .

**Comment by c-w** [comment]
@NatashaSvic Could you please post a stacktrace of the new error?

**Comment by NatashaSvic** [comment]
> stacktrace

MacBook-Pro:app user$ python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
May 13, 2019 - 11:44:02
Django version 2.0, using settings 'app.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10baa0048>
Traceback (most recent call last):
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 44, in get_internal_wsgi_application
    return import_string(app_path)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/Users/user/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/user/doccano/app/app/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 140, in __init__
    self.load_middleware()
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 37, in load_middleware
    middleware = import_string(middleware_path)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/Users/user/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'applicationinsights'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 140, in inner_run
    handler = self.get_handler(*args, **options)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 65, in get_handler
    return get_internal_wsgi_application()
  File "/Users/user/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 49, in get_internal_wsgi_application
    ) from err
django.core.exceptions.ImproperlyConfigured: WSGI application 'app.wsgi.application' could not be loaded; Error importing module.


<img width="1093" alt="Screenshot 2019-05-13 at 13 48 01" src="https://user-images.githubusercontent.com/35193765/57619278-d075ec00-7585-11e9-80b0-def63488d661.png">

**Comment by c-w** [comment]
Looks like `applicationinsights` can't be found for some reason although it's declared in `requirements.txt`. Could you post the result of `pip freeze`?

**Comment by c-w** [comment]
All the dependencies except for applicationinsights are there. What's the output of `pip install applicationinsights==0.11.7`?

**Comment by NatashaSvic** [comment]
> All the dependencies except for applicationinsights are there. What's the output of `pip install applicationinsights==0.11.7`?
Thanks a lot for your help, much appreciated! 

Installed the new dependency and now it runs into encoding issues:

  File "/Users/user/anaconda3/lib/python3.7/locale.py", line 495, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

Overall, the `requirements.txt` missed a lot of dependencies in my case. For example, I had to debug all the way through Django since it was not listed in the requirements. When I run the doccano server directly from the docker image in a VM, it works. On my native machine, it works only when I delete the image and then re-initiate it. Running the server once it's been stared and then stopped, does not work. 

`docker rm <container>`
`docker container ls`
`docker run -d --name doccano -p 8000:80 chakkiworks/doccano`

then it works, but I lose all my projects and need to create user profiles from scratch.

**Comment by c-w** [comment]
There must be something strange with the host system so perhaps moving to Docker is the best option.

To remove the need for the `docker rm`, you can start the container like this `docker run --rm ...` so that it will be automatically removed on exit.

In order to preserve the database across restarts, you can try this `docker run -v /path/to/some/folder/db.sqlite3:/doccano/app/db.sqlite3 ...` so that the database file will be stored outside of the container.

**Comment by NatashaSvic** [comment]
> There must be something strange with the host system so perhaps moving to Docker is the best option.
> 
> To remove the need for the `docker rm`, you can start the container like this `docker run --rm ...` so that it will be automatically removed on exit.
> 
> In order to preserve the database across restarts, you can try this `docker run -v /path/to/some/folder/db.sqlite3:/doccano/app/db.sqlite3 ...` so that the database file will be stored outside of the container.

`docker start doccano` did the job eventually. The Django app still doesn't work for me but I'll stick to this now. Thank you very much for helping @c-w

**Comment by c-w** [comment]
There's also the new option to start the stack with `docker-compose up`. Could you give that a try and let me know if it works for you?

**Comment by NatashaSvic** [comment]
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml @

> There's also the new option to start the stack with `docker-compose up`. Could you give that a try and let me know if it works for you?

**Comment by c-w** [comment]
Please update to the latest version of the code.

**Comment by icoxfog417** [comment]
Please raise a new issue if you still face this phenomenon.
