### ISSUE TITLE
Deploy to Azure stopped working 

### ISSUE THREAD

**Issue by roiza** [chakki-works/doccano#203]
Hey
Deploying to Azure stopped working.  yesterday I noticed that my instance was down. A new deployment to a new resource group failed as well with the same error.
The issues seem to be related to furl URL validation

I tried to reproduce the error by installing furl 2.0.0 on my local machine and invoking furl(url,'') but I could not reproduce it. 

Running the dockerized version on a local container seems to work as well. 

To reproduce the issue - just click on the "Deploy to azure" button in the main README of the repo. 

------------------------

### System information
Azure

### Source code / logs (formatted log here: https://pastebin.com/S9yXVEcK)
`2019_05_16_RD0003FF688799_default_docker.log:
2019-05-16T00:31:53.737046000Z Traceback (most recent call last):
2019-05-16T00:31:53.737099802Z   File "app/manage.py", line 15, in <module>
2019-05-16T00:31:53.737112703Z     execute_from_command_line(sys.argv)
2019-05-16T00:31:53.737121803Z   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
2019-05-16T00:31:53.737133604Z     utility.execute()
2019-05-16T00:31:53.737142004Z   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 325, in execute
2019-05-16T00:31:53.737150805Z     settings.INSTALLED_APPS
2019-05-16T00:31:53.737159205Z   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
2019-05-16T00:31:53.737168206Z     self._setup(name)
2019-05-16T00:31:53.737176406Z   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 44, in _setup
2019-05-16T00:31:53.737184906Z     self._wrapped = Settings(settings_module)
2019-05-16T00:31:53.737193107Z   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 107, in __init__
2019-05-16T00:31:53.737201807Z     mod = importlib.import_module(self.SETTINGS_MODULE)
2019-05-16T00:31:53.737210507Z   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
2019-05-16T00:31:53.737219908Z     return _bootstrap._gcd_import(name[level:], package, level)
2019-05-16T00:31:53.737228408Z   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
2019-05-16T00:31:53.737236909Z   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
2019-05-16T00:31:53.737245409Z   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
2019-05-16T00:31:53.737253909Z   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
2019-05-16T00:31:53.737262410Z   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
2019-05-16T00:31:53.737271010Z   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2019-05-16T00:31:53.737279511Z   File "/doccano/app/app/settings.py", line 204, in <module>
2019-05-16T00:31:53.737287911Z     ssl_require='sslmode' not in furl(env('DATABASE_URL', '')).args,
2019-05-16T00:31:53.737296211Z   File "/usr/local/lib/python3.6/site-packages/furl/furl.py", line 1310, in __init__
2019-05-16T00:31:53.737306712Z     self.load(url)  # Raises ValueError on invalid url.
2019-05-16T00:31:53.737315112Z   File "/usr/local/lib/python3.6/site-packages/furl/furl.py", line 1337, in load
2019-05-16T00:31:53.737323513Z     self.netloc = tokens.netloc  # Raises ValueError in Python 2.7+.
2019-05-16T00:31:53.737331713Z   File "/usr/local/lib/python3.6/site-packages/furl/furl.py", line 1801, in __setattr__
2019-05-16T00:31:53.737340013Z     object.__setattr__(self, attr, value)
2019-05-16T00:31:53.737348114Z   File "/usr/local/lib/python3.6/site-packages/furl/furl.py", line 1464, in netloc
2019-05-16T00:31:53.737364115Z     self.host = host
2019-05-16T00:31:53.737375315Z   File "/usr/local/lib/python3.6/site-packages/furl/furl.py", line 1801, in __setattr__
2019-05-16T00:31:53.737384416Z     object.__setattr__(self, attr, value)
2019-05-16T00:31:53.737392616Z   File "/usr/local/lib/python3.6/site-packages/furl/furl.py", line 1379, in host
2019-05-16T00:31:53.737401116Z     raise ValueError(errmsg % (host, INVALID_HOST_CHARS))
2019-05-16T00:31:53.737409317Z ValueError: Invalid host 'user:password@db-instance-url.azure.com'. Host strings must have at least one non-period character, can't contain any of '!@#$%^&'"*()+=:;/', and can't have adjacent periods.`

**Comment by c-w** [comment]
Thanks for reporting this. In the Azure deploy the database user is in the format `user@server` and it looks like furl doesn't deal well with that. Looks like URL-encoding the `@` to `%40` fixes the problem.

**Comment by roiza** [comment]
Thanks!

**Comment by c-w** [comment]
@roiza Just wanted to let you know that the fix is now merged so you should be able to deploy via the ARM template without issues going forward. You may also be interested in this upcoming pull request https://github.com/chakki-works/doccano/pull/208 which adds automated incremental deployments via Azure Pipelines.

**Comment by roiza** [comment]
Thanks!
I ended up modifying the container settings in Azure UI and restarting it.
