### ISSUE TITLE
Running tests fails on import and there is no documentation on testing.

### ISSUE THREAD

**Issue by alexQueue** [chakki-works/doccano#214]
### System information
- Mac OS Mojave
- (brew) Python 3.6.4

### Describe the problem
Tests are either failing, or are poorly documented (or both). I can't get them to run properly and so therefore I'm not sure if I'm using the correct testrunner or if there's an issue with my system. There is not documentation about testing so I don't know if the command is wrong. 

This is on current master with no changes.

### Source code / logs
```
$ python3 manage.py test

Creating test database for alias 'default'...
System check identified no issues (0 silenced).

Running tests...
----------------------------------------------------------------------
EEE
======================================================================
ERROR [0.005s]: app.app (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: app.app
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
ModuleNotFoundError: No module named 'app.app'


======================================================================
ERROR [0.000s]: app.classifier (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: app.classifier
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
ModuleNotFoundError: No module named 'app.classifier'


======================================================================
ERROR [0.000s]: app.server (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: app.server
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
ModuleNotFoundError: No module named 'app.server'
```

**Comment by alexQueue** [comment]
I found the proper command is to run ./tools/ci.sh, but I maintain that this should be documented as well.

**Comment by c-w** [comment]
@alexQueue This is now documented in the README.
