### ISSUE TITLE
Sequence to sequence: cannot download labels

### ISSUE THREAD

**Issue by raibosome** [chakki-works/doccano#268]
### System information
- macOS 10.14
- Python 3.6

### Describe the problem
Ran the Docker image as a container. Created a sequence to sequence project and imported a one-column .txt file. Managed to annotate the data and the annotations persist but I notice that:

1.  Progress bar shows 0/0 despite having imported data.
2. No statistics available.
3. Cannot export data.

### Source code / logs

[Here](https://github.com/chakki-works/doccano/files/3341857/testing.txt) is the data that I imported. Below is a screenshot that shows the progress bar is at 0/0.

<img width="1674" alt="image" src="https://user-images.githubusercontent.com/11023859/60383923-923b7a00-9aaa-11e9-8885-d84a83ccbf18.png">

Logs for viewing statistics.

```
Internal Server Error: /v1/projects/4/statistics
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/doccano/app/api/views.py", line 70, in get
    label_count, user_count = self.label_per_data(p)
  File "/doccano/app/api/views.py", line 94, in label_per_data
    for d in annotations.values('label__text', 'user__username').annotate(Count('label'), Count('user')):
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 750, in values
    clone = self._values(*fields, **expressions)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 745, in _values
    clone.query.set_values(fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1987, in set_values
    self.add_fields(field_names, True)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1735, in add_fields
    join_info = self.setup_joins(name.split(LOOKUP_SEP), opts, alias, allow_many=allow_m2m)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1473, in setup_joins
    names[:pivot], opts, allow_many, fail_on_missing=True,
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1389, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'label' into field. Choices are: created_at, document, document_id, id, manual, prob, text, updated_at, user, user_id
```

Logs for downloading labeled data.

```
Internal Server Error: /v1/projects/4/docs/download
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/doccano/app/api/views.py", line 312, in get
    data = painter.paint(documents)
  File "/doccano/app/api/utils.py", line 412, in paint
    data = super().paint(documents)
  File "/doccano/app/api/utils.py", line 385, in paint
    a.pop('prob')
KeyError: 'prob'
```

**Comment by icoxfog417** [comment]
Thank you for reporting. We confirm this on master branch (at 9d7cbfe0c680a03b453062299751778c2655a6d7). Please wait until the fix 🙏

**Comment by DerekChia** [comment]
Can we know what the latest working commit that does not have this bug? Thanks

**Comment by savkov** [comment]
Any estimate on when the #287 PR will be merged/released? If it's soon I may as well wait for it instead of using the latest commit.
