### ISSUE TITLE
Cannot delete labels and annoate entities

### ISSUE THREAD

**Issue by jtangchi** [chakki-works/doccano#54]
### System information
- Linux Ubuntu 16.04
- Python version: 3.6

### Describe the problem
Bug report.
I follow the tutorial and try to annotate few simple entities such as Location, Person, etc.
I upload the sample data(text format, each line is a sentence without line break).
Two bugs are both related to django database (sqlite3 in my case) issue.
1) I cannot delete the labels I created in Label editor section.
2) I cannot annotate entity in Annotate Data section.

I have spent few hours reading the source code and trying to debug the issue. However, I didn't find the solution. I printed out the some logs. The query indicates a insertion into table 'server_sequenceannotation', however, the error shows django.db.utils.OperationalError: no such table: main.server_label__old which doesnot exist in the sqlite3 tables. The 'using' parameter in the traceback error is 'default'. I suspect this might be the reason but I am not very sure.
Please help with any suggestion. Very much appreciate it!

### Source code / logs
Traceback for case1:

Traceback (most recent call last):
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: main.server_document__old

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/rest_framework/generics.py", line 293, in delete
    return self.destroy(request, *args, **kwargs)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/rest_framework/mixins.py", line 93, in destroy
    self.perform_destroy(instance)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/rest_framework/mixins.py", line 97, in perform_destroy
    instance.delete()
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/models/base.py", line 891, in delete
    return collector.delete()
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/models/deletion.py", line 283, in delete
    count = qs._raw_delete(using=self.using)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/models/query.py", line 676, in _raw_delete
    return sql.DeleteQuery(self.model).delete_qs(self, using)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/models/sql/subqueries.py", line 75, in delete_qs
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1066, in execute_sql
    cursor.execute(sql, params)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: main.server_document__old
[27/Dec/2018 04:41:14] "DELETE /api/projects/1/labels/1 HTTP/1.1" 500 21810

-----------------------------------------------------------------------------------------------------------------------
Traceback for case2:

Internal Server Error: /api/projects/1/docs/1/annotations/
Traceback (most recent call last):
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: main.server_label__old

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/rest_framework/generics.py", line 244, in post
    return self.create(request, *args, **kwargs)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/home/chitang/sourcecodes/doccano/app/server/api.py", line 134, in perform_create
    serializer.save(document=doc, user=self.request.user)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/home/chitang/sourcecodes/doccano/app/server/serializers.py", line 59, in create
    annotation = SequenceAnnotation.objects.create(**validated_data)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/models/query.py", line 417, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/models/base.py", line 842, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/models/base.py", line 880, in _do_insert
    using=using, raw=raw)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/models/query.py", line 1125, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1283, in execute_sql
    cursor.execute(sql, params)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/chitang/anaconda3/envs/py3/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: main.server_label__old
[27/Dec/2018 04:44:44] "POST /api/projects/1/docs/1/annotations/ HTTP/1.1" 500 23012

**Comment by BrambleXu** [comment]
Please see this #51.
You can first try to update Django to 2.1.4. If it does not work, try to downgrade SQLite to 3.25.3.
Please give us some feedback which method solves this problem.
