### ISSUE TITLE
Migrate failed

### ISSUE THREAD

**Issue by lhwlhw90** [chakki-works/doccano#71]
If you open a GitHub issue, here is our policy:

1. It must be a bug, a feature request, or a significant problem with documentation (for small docs fixes please send a PR instead).
2. The form below must be filled out.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: windows 10
- **Python version**:  python 3.6

### Describe the problem
I migrate on mysql cause an error: 
django.db.utils.OperationalError: (1170, "BLOB/TEXT column 'text' used in key specification without a key length")

### Source code / logs
(venv) D:\project\doccano-master\app>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, server, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying server.0001_initial...Traceback (most recent call last):
  File "D:\project\doccano-master\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "D:\project\doccano-master\venv\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "D:\project\doccano-master\venv\lib\site-packages\MySQLdb\cursors.py", line 198, in execute
    res = self._query(query)
  File "D:\project\doccano-master\venv\lib\site-packages\MySQLdb\cursors.py", line 304, in _query
    db.query(q)
  File "D:\project\doccano-master\venv\lib\site-packages\MySQLdb\connections.py", line 217, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1170, "BLOB/TEXT column 'text' used in key specification without a key length")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "D:\project\doccano-master\venv\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "D:\project\doccano-master\venv\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\project\doccano-master\venv\lib\site-packages\django\core\management\base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\project\doccano-master\venv\lib\site-packages\django\core\management\base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "D:\project\doccano-master\venv\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "D:\project\doccano-master\venv\lib\site-packages\django\core\management\commands\migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "D:\project\doccano-master\venv\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "D:\project\doccano-master\venv\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "D:\project\doccano-master\venv\lib\site-packages\django\db\migrations\executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "D:\project\doccano-master\venv\lib\site-packages\django\db\migrations\migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "D:\project\doccano-master\venv\lib\site-packages\django\db\migrations\operations\models.py", line 514, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "D:\project\doccano-master\venv\lib\site-packages\django\db\backends\base\schema.py", line 360, in alter_unique_together
    self.execute(self._create_unique_sql(model, columns))
  File "D:\project\doccano-master\venv\lib\site-packages\django\db\backends\base\schema.py", line 133, in execute
    cursor.execute(sql, params)
  File "D:\project\doccano-master\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "D:\project\doccano-master\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\project\doccano-master\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\project\doccano-master\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "D:\project\doccano-master\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\project\doccano-master\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "D:\project\doccano-master\venv\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "D:\project\doccano-master\venv\lib\site-packages\MySQLdb\cursors.py", line 198, in execute
    res = self._query(query)
  File "D:\project\doccano-master\venv\lib\site-packages\MySQLdb\cursors.py", line 304, in _query
    db.query(q)
  File "D:\project\doccano-master\venv\lib\site-packages\MySQLdb\connections.py", line 217, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1170, "BLOB/TEXT column 'text' used in key specification without a key length")

**Comment by icoxfog417** [comment]
Thank you for reporting the issue, but please describe a phenomenon you faced based on the issue template.

**Comment by BrambleXu** [comment]
Delete all file in migrations folder and run `python manage.py migrate` again.

**Comment by lhwlhw90** [comment]
> This is not a bug. You changed the models.py file a lot and it might have conflicts with the data you already stored.
> 
> * Delete all your projects.
> * Delete all files in migrations folder (optional)
> * Run `python manage.py migrate` again.
> 
> If there are still errors, you have to solve the conflicts first.

I clone a new project and clean all database then perform migrate .the problem still occurs.

**Comment by BrambleXu** [comment]
I cloned the new doccano and it works well. Might be the SQL version problem. 
https://github.com/chakki-works/doccano/issues/51#issuecomment-449839533

**Comment by lhwlhw90** [comment]
> I cloned the new doccano and it worked well. Your problem might be the SQL version.
> [#51 (comment)](https://github.com/chakki-works/doccano/issues/51#issuecomment-449839533)

I make postgresql as backend to replace mysql.the problem resolved

**Comment by hankcs** [comment]
Well, the current version still doesn't work with MySQL.
