### ISSUE TITLE
Exception: Instrumentation key was required but not provided

### ISSUE THREAD

**Issue by louisguitton** [chakki-works/doccano#83]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.14.2
- **Python version**: 3.7

### Describe the problem
Can't run the docker image: an exception occurs that is related to Azure. It might be due to https://github.com/chakki-works/doccano/pull/72

### Source code / logs
To reproduce `docker run -p 8080:80 doccano:1`

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/doccano/app/app/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 136, in __init__
    self.load_middleware()
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 36, in load_middleware
    mw_instance = middleware(handler)
  File "/usr/local/lib/python3.6/site-packages/applicationinsights/django/middleware.py", line 109, in __init__
    self._client = common.create_client(self._settings)
  File "/usr/local/lib/python3.6/site-packages/applicationinsights/django/common.py", line 74, in create_client
    client = applicationinsights.TelemetryClient(aisettings.ikey, channel)
  File "/usr/local/lib/python3.6/site-packages/applicationinsights/TelemetryClient.py", line 28, in __init__
    raise Exception('Instrumentation key was required but not provided')
Exception: Instrumentation key was required but not provided
```

**Comment by BrambleXu** [comment]
I test it in macOS 10.13.6 with docker 2.0.0.0-mac81 (29211), and there is no such problem.

**Comment by talf** [comment]
I get exactly the same error on Amazon Linux 2 with docker 18.06.1-ce

**Comment by fabrichter** [comment]
I managed to circumvent the issue by commenting out `ENV AZURE_APPINSIGHTS_IKEY=""` in the Dockerfile. Hope this helps as a temporary workaround and in finding the underlying issue.

**Comment by louisguitton** [comment]
@fabrichter nice one, the fix works for me.
You're right in saying that it's linked #76 and not #72 , at least according to git blame.

**Comment by Hironsan** [comment]
# Problem

I found the cause. In line 71 of `applicationinsights/django/common.py`, there is the following logic: 

```python
ikey = aisettings.ikey
if ikey is None:
    return dummy_client("No ikey specified")
```

where `ikey` is assigned according to `AZURE_APPINSIGHT_IKEY`.

If there is no `AZURE_APPINSIGHT_IKEY` in environment variables, `ikey` is `None`. It doesn't cause any problems. But if there is `AZURE_APPINSIGHT_IKEY` with empty string, `ikey` is not `None`. As a result, the exception is raised in line 74.

```python
client = applicationinsights.TelemetryClient(aisettings.ikey, channel)
```

# Solution

I came up with two solutions.

## Solution1: Update settings.py

The problem is caused due to an empty string. So if `AZURE_APPINSIGHTS_IKEY` is empty, it will be converted to `None`:

```python
AZURE_APPINSIGHTS_IKEY = os.getenv('AZURE_APPINSIGHTS_IKEY')
APPLICATION_INSIGHTS = {
    'ikey': AZURE_APPINSIGHTS_IKEY if AZURE_APPINSIGHTS_IKEY else None,
}
```

## Solution2: Delete `AZURE_APPINSIGHT_IKEY` from Dockerfile and pass it when executing docker run command

First, delete `AZURE_APPINSIGHTS_IKEY` from Dockerfile:

```
# Delete
# ENV AZURE_APPINSIGHTS_IKEY=""
```

Then pass it to a docker container when executing docker run command:

```bash
$ docker run -p 8000:80 -e AZURE_APPINSIGHTS_IKEY=SOMEKEY doccano
```
